### ISSUE TITLE
Mouse clicks don't work on Wayland

### ISSUE THREAD

**Issue by jannuary** [nlogozzo/NickvisionTagger#11]
Clicking anything does nothing. Scrolling and keyboard nav works fine, but it seems that mouse clicks specifically get eaten.

**Comment by nlogozzo** [comment]
Like nothing works? Clicking the ListView doesn't select files, clicking headerbar buttons don't do anything, etc??
This is a weird issue.
Could you lunch the application from the terminal './NickvisionTagger' from the directory you have the file in and send me the output of the terminal. Maybe that has some output to what is going on

**Comment by jannuary** [comment]
Only complains about curl, which doesn't seem relevant:
`./NickvisionTagger: /lib64/libcurl.so.4: no version information available (required by ./NickvisionTagger)

Using X11, it works though, so wonder what's the deal here.

**Comment by nlogozzo** [comment]
I'm using X11 on my system since I have nvidia drivers which explains why I'm not seeing an issue.

**Comment by nlogozzo** [comment]
Could this be an adwaita issue?

**Comment by jannuary** [comment]
Adwaita doesn't have anything to do with input.

**Comment by nlogozzo** [comment]
I meant as libadwaita/gtk4
I don't touch anything that has to do with input :man_shrugging:

**Comment by nlogozzo** [comment]
Could you try building the latest commit in the 2022.5.3 branch and running that? I replaced all button clicked signals with bounded actions instead and I want to see if that fixes the issue.

**Comment by nlogozzo** [comment]
@arun54321 Could you try too ^

**Comment by jannuary** [comment]
No, does the same. Of course, I don't think that would've affected it anyway - signals should work fine and it's not limited to buttons either.

**Comment by jannuary** [comment]
Desktop, Fedora 36, amdgpu.

**Comment by nlogozzo** [comment]
Ok I have a laptop home with intel drivers that I can run a wayland session off of with Manjaro. I'll do some investigating once I get home

**Comment by nlogozzo** [comment]
No issues on Wayland for me:
![image](https://user-images.githubusercontent.com/17648453/171055929-d9bab2ef-9c22-4e47-88fc-03dab787cea2.png)

**Comment by nlogozzo** [comment]
@jannuary Have you tried the flatpak version of the app? Does this issue still occur when running the flatpak?

**Comment by daudix-UFO** [comment]
I use wayland and i have no issues with clicks

**Comment by jannuary** [comment]
This is not an issue on flatpak, still, very perculiar

**Comment by daudix-UFO** [comment]
Maybe somthing with dependencies?

_А так, я думаю лучше использовать flatpak_
