### ISSUE TITLE
Build error on debian

### ISSUE THREAD

**Issue by CountOmega** [nlogozzo/NickvisionTagger#13]
When I am trying to build your program in debian, it doesn't build. Log:
```
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gtk4'
--   Found gtk4, version 4.6.4
-- Checking for module 'libadwaita-1'
--   Found libadwaita-1, version 1.1.1
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.9.5
-- Checking for module 'curlpp'
--   Found curlpp, version 0.8.1
-- Checking for module 'taglib'
--   Found taglib, version 1.12
-- Checking for module 'libmusicbrainz5'
--   Found libmusicbrainz5, version 5.1.0
CMake Error at CMakeLists.txt:44 (include):
  include could not find requested file:

    GlibCompileResourcesSupport

```
I have all the dev dependencies installed. I thought` libglibmm-2.4-dev` should provide the glib stuff needed, but I still get the warning.

**Comment by nlogozzo** [comment]
Hi @CountOmega 

The GlibCompileResourcesSupport comes from [GCR_CMake](https://github.com/Makman2/GCR_CMake) . You need to clone this repository and change this line: `list(APPEND CMAKE_MODULE_PATH /home/nlogozzo/Documents/Programming/GCR_CMake/macros)` at the bottom of the cmake file to the path where you cloned the repo.

**Comment by nlogozzo** [comment]
Closing. If you have any other issues let me know
