### ISSUE TITLE
How to install from releases tar.gz?

### ISSUE THREAD

**Issue by arun54321** [nlogozzo/NickvisionTagger#2]

**Comment by nlogozzo** [comment]
The tar.gz releases are uninstallable. All you need to do in download the tar.gz file, extract it, and run the application from within the extracted directory.

**Comment by nlogozzo** [comment]
Will be looking to add the application to flathub this weekend

**Comment by nlogozzo** [comment]
See #5 to track.

**Comment by arun54321** [comment]
It didn't run properly when executing it. Close button didn't work and I cannot drag the app.  So I thought I should've install gresource and XML to /use/share.

**Comment by nlogozzo** [comment]
As long as you keep the gresource and gresource.xml file within the same directory as the exe it should run fine.

**Comment by nlogozzo** [comment]
Could you lunch the application from the terminal './NickvisionTagger' from the directory you have the file in and send me the output of the terminal. It should tell u what the problem is.

**Comment by arun54321** [comment]
```
./NickvisionTagger
./NickvisionTagger: /lib64/libcurl.so.4: no version information available (required by ./NickvisionTagger)
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension

```

**Comment by nlogozzo** [comment]
> ```
> ./NickvisionTagger
> ./NickvisionTagger: /lib64/libcurl.so.4: no version information available (required by ./NickvisionTagger)
> dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
> dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
> dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
> ```
> 
> I get `driver is missing backgroundCallable V2 extension` on all gnome apps, they work fine. so I don't think it an issue.

`./NickvisionTagger: /lib64/libcurl.so.4: no version information available (required by ./NickvisionTagger)` this line is the culprit
NickvisionTagger requires curlpp as a dependency. The list of the dependencies are seen at the bottom of the readme:
```
Dependencies:
- [gtk4](https://gtk.org/)
- [libadwaita](https://gnome.pages.gitlab.gnome.org/libadwaita/)
- [curlpp](http://www.curlpp.org/)
- [jsoncpp](https://github.com/open-source-parsers/jsoncpp)
- [taglib](https://taglib.org/)
```
Please make sure they are installed before running the application.

**Comment by arun54321** [comment]
I have already installed curlpp. it won't even open if it does not exist in the system.
https://user-images.githubusercontent.com/42943340/170828210-ab5c0ef6-aa17-4bea-b165-6f5ab59ed423.mp4

**Comment by arun54321** [comment]
```
~ ❯ pkcon install jsoncpp
Resolving                     [=========================]         
Loading cache                 [=========================]         
Testing changes               [=========================]         
Finished                      [=========================]         
Fatal error: jsoncpp-1.9.5-2.fc36.x86_64 is already installed
~ ❯ pkcon install taglib
Resolving                     [=========================]         
Finished                      [=========================]         
Fatal error: taglib-1.12-6.fc36.x86_64 is already installed
~ ❯ pkcon install curlpp
Resolving                     [=========================]         
Finished                      [=========================]         
Fatal error: curlpp-0.8.1-17.fc36.x86_64 is already installed

```

**Comment by nlogozzo** [comment]
Could you try `pkcon install libcurl` ?

**Comment by arun54321** [comment]
it is already installed.
```
~ ❯ sudo dnf install libcurl
Last metadata expiration check: 0:00:08 ago on Sat 28 May 2022 
Package libcurl-7.82.0-5.fc36.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

```

**Comment by nlogozzo** [comment]
Hmm...this is very weird. Once I get back to my computer I will investigate more. I'm planning to release a flatpak version of the app anyway so soon you could just use that.

**Comment by nlogozzo** [comment]
Oh I think I know why...your on fedora right? 
Fedora has separate dev packages for each package. 
Try adding -dev to each package name and install said dev version and then try running the app. 
I probably should've compiled the app in release mode that probably would've helped.

**Comment by arun54321** [comment]
Dev/devel packages are needed for compiling the app from source. Not for running them. Anyways I will wait for flatpak.

**Comment by nlogozzo** [comment]
Weird 🤷🏻‍♂️ gives me no problem on all my Manjaro machines

**Comment by nlogozzo** [comment]
@arun54321 Still no Flatpak however I released a new version this time compiling with release mode. Could you try it, just curious to see what happens

**Comment by arun54321** [comment]
Same issue. Cannot interact with any buttons.

**Comment by nlogozzo** [comment]
Hmm

**Comment by nlogozzo** [comment]
Could be related to #11

**Comment by arun54321** [comment]
Now I switched to x11 and it works now.

**Comment by nlogozzo** [comment]
:+1: trying to investigate the wayland issue. Use #11 to track
