### ISSUE TITLE
Make UI Translateable

### ISSUE THREAD

**Issue by Vistaus** [nlogozzo/NickvisionTagger#24]
It would be great if this app could be translated. When that's made possible, I'll provide the Dutch translation. :-)

**Comment by daudix-UFO** [comment]
And I will translate to russian

**Comment by nlogozzo** [comment]
Translation support is here (Implemented using gettext)! https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.11.0-beta1

**Comment by nlogozzo** [comment]
Please submit a PR with your translations by Nov 10, 2022 to be included in the V2022.11.0 stable release for this week.

**Comment by nlogozzo** [comment]
Thank you everyone for your help with translating this application, making it accessible to more people than ever before. A stable release will be released this week by Nov 10, 2022 with your translations :)
I'm closing this issue as completed since the translation infrastructure is complete.
