### ISSUE TITLE
tagger doesn't work with musicbrainz (or it seems so)

### ISSUE THREAD

**Issue by legacychimera247** [nlogozzo/NickvisionTagger#25]
everytime i try to use the musicbrainz feature tagger seems to search for something and then just does nothing, maybe a confirmation doing something would be good? (if it's actually doing something)

**Comment by nlogozzo** [comment]
The library used to access musicbrainz, libmusicbrainz5, seems to be a little outdated for accessing musicbrainz, I have noticed. I will be looking for either another music database or a better way to accessing musicbrainz to also complete #18.

**Comment by nlogozzo** [comment]
As of now, Tagger will only get the year, album, and album artist from musicbrainz if available.

**Comment by legacychimera247** [comment]
by the way, don't think you can add chromaprint support for tagging song by listening them, right?

**Comment by nlogozzo** [comment]
It looks like a C library so I should be able to include it. That'll make it a lot easier with MusicBrainz searching as well.

**Comment by nlogozzo** [comment]
I've decided to scrap the MusicBrainz feature using libmusicbrainz5 completely in the next version, until I can find a more suitable library for this task.

**Comment by legacychimera247** [comment]
oh ok, that's a shame, weird anyway cause ex-falso is working almost the same way as picard...

**Comment by nlogozzo** [comment]
Those softwares are written in python with those APIs for MusicBrainz easily available and more up to date than C++ libraries.
I will have to take a look at the python library used by those programs and probably have to port it over to C++, which may take some time.

**Comment by nlogozzo** [comment]
Added chromaprint support: https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.1

**Comment by nlogozzo** [comment]
Now that chromaprint is in place, expect MusicBrainz search for the next release.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.2-beta1

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.2
