### ISSUE TITLE
[Feature] Sync with musicbrainz.org

### ISSUE THREAD

**Issue by nacho-domatix** [nlogozzo/NickvisionTagger#3]
I guess this won't ever happen, but I'd love to see a GTK/GNOME app that can connect to musicbrainz.org to get all the info.

I know the target of this app probably isn't this one, but it's been years since I edited manually my tags. Sync with internet database and automatizacion is a nice goal to achieve with this kind of programs :)

**Comment by nlogozzo** [comment]
Great idea! Will look to implement this weekend!

**Comment by nlogozzo** [comment]
Looks like musicbrainz already offers C++ APIs for complete this task: [](https://musicbrainz.org/doc/Developer_Resources)

Hopefully it won't be too complicated to get it working within the app.

**Comment by nlogozzo** [comment]
Quick question: How would you like this feature to look?

1. You have a random file and you just want to click the button and it will fill in all the metadata about it.
2. You have a random file, with at least the artist and title set, and you click the button and it will fill in the remaining/missing metadata

Option 2 seems like what is supported by the API, with option 1 going to be a complicated task.

**Comment by nacho-domatix** [comment]
Option 2 indeed. I can't see how you can get the info without at least the artist and title, that really sound complicated (and quite inaccurate). A problem cold be when the song matches different albums (which is almost always), extra metadata can help, but in the end, user should be able to choose). Album photo should be retrieved as well.

Extra cool options can be "group files" (as Picard does) and rename files after changing the metadata info (no matter if it has been manually or getting it online). In the prefs should be the pattern (like /artist/year/album/...)

Thanks for your great work! I think you found a big gap for GNOME users! :)

**Comment by nlogozzo** [comment]
> Option 2 indeed. I can't see how you can get the info without at least the artist and title, that really sound complicated (and quite inaccurate). A problem cold be when the song matches different albums (which is almost always), extra metadata can help, but in the end, user should be able to choose). Album photo should be retrieved as well.

That's what I was thinking. However, in terms of UX, should we assume the user to know they need to have the title and artist set? I was thinking of showing the dialog when the user attempts to use this download function: 
![image](https://user-images.githubusercontent.com/17648453/170842588-eb307b07-3a85-498e-b85c-cefb62f3f4c2.png)

**Comment by nacho-domatix** [comment]
I wouldn't show anything that can bother the user whenever things are doing fine. If the info is not enough, just show it *after* trying to retrieve the info. IMHO.

**Comment by nlogozzo** [comment]
[V2022.5.1](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.5.1)
Right now the date and album will be gathered from MusicBrainz if available.
In the next release when #4 is implemented, downloading and applying the album art from MusicBrainz will be implemented release as well :)
