### ISSUE TITLE
Ability to drag files and folders into the app

### ISSUE THREAD

**Issue by emiliogonzalezjunior** [nlogozzo/NickvisionTagger#30]
It would be great if that Tagger app could accept files and folders that are dragged into the app, this very useful when dealing wit big collections and folders from different sources. I thing this is one of the last features that not make me fully switch from Kid3 to Tagger.

**Comment by nlogozzo** [comment]
I might not be able to add dragging files and folders into the app, but I will add an option to settings that will allow you to add multiple folder sources instead of opening an individual folder like we do now.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/commit/a30e0d5a5709913748b04bc1c339e69507c9877f

**Comment by nlogozzo** [comment]
Added the ability to drag a music folder into the app to open it.

**Comment by nlogozzo** [comment]
However, it is limited to only one music folder at a time, as that is the current UX of the app.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.8.0
