### ISSUE TITLE
Making the app mobile responsive

### ISSUE THREAD

**Issue by mbeps** [nlogozzo/NickvisionTagger#31]
# Best example (Geary Email Client):
![Screenshot from 2022-06-23 18-41-47](https://user-images.githubusercontent.com/58662575/175361440-13b580ee-60d8-4947-9853-7a388f324d64.png)

![Screenshot from 2022-06-23 18-41-56](https://user-images.githubusercontent.com/58662575/175361504-ce2c4846-eb3c-4e78-bc5e-892e39f2e132.png)

# Very Rough Sketch
![tagger](https://user-images.githubusercontent.com/58662575/175361736-b0b12688-8e5e-45b0-97ec-cc0ad7ea0669.png)

**Comment by nlogozzo** [comment]
Tagger is an app focused on the desktop. I don't really see it being used on mobile devices.
