### ISSUE TITLE
Unable to run Tagger Flatpak on Ubuntu

### ISSUE THREAD

**Issue by manikandancode** [nlogozzo/NickvisionTagger#34]
Ubuntu 22.04 Wayland
Just tried to add folder to load file after fresh install. And Crash.  Tested more than 5 times with fresh install but same problem.
Thanks.

![Screenshot from 2022-06-25 13-47-28](https://user-images.githubusercontent.com/46480489/175774999-5acc7a57-061c-4df0-a018-cd5dde7b7ffb.png)

**Comment by nlogozzo** [comment]
According to the error, `cannot increment recursive directory iterator: Permission denied` . This means that Tagger was unable to open a subfolder in the folder you opened. 
What folder did you try opening?

**Comment by manikandancode** [comment]
Downloads

**Comment by nlogozzo** [comment]
Is there any file, doesn't have to be a music file, inside your downloads directory that just happens to have a lock next to it in Nautilus, meaning that you don't have access to the file?

**Comment by manikandancode** [comment]
yes

**Comment by nlogozzo** [comment]
Can you go to the folder `~/.var/app/org.nickvision.tagger/config/Nickvision/NickvisionTagger` and delete the config.json file, then open Tagger again, reopened your folder and see what happens.

**Comment by manikandancode** [comment]
After deleting config


![Screenshot from 2022-09-22 20-35-50](https://user-images.githubusercontent.com/46480489/191786879-37b65e46-6c03-45ac-9309-80c84bb81132.png)

**Comment by nlogozzo** [comment]
Can you go to that same directory above but this time open the `config.json` and send here the results.

**Comment by nlogozzo** [comment]
Then you can also try: https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.0-beta4

**Comment by manikandancode** [comment]
> Can you go to that same directory above but this time open the `config.json` and send here the results.

{
	"IncludeSubfolders" : true,
	"IsFirstTimeOpen" : false,
	"LastOpenedFolder" : "/home/manikandan",
	"PreserveModificationTimeStamp" : false,
	"RememberLastOpenedFolder" : true,
	"Theme" : 0
}

**Comment by manikandancode** [comment]
> Then you can also try: https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.0-beta4

Fixed. :fire: Thanks.

file:///home/manikandan/MEGA/connectwww/images/Screenshot%20from%202022-09-23%2012-28-09.png

**Comment by nlogozzo** [comment]
Great! A stable version should be released on flathub this weekend :)
