### ISSUE TITLE
Remember Tag to Filename Preference

### ISSUE THREAD

**Issue by CloneMMDDCVII** [nlogozzo/NickvisionTagger#36]
Currently, when using [Tag to Filename] repeatedly, there is an extra step of needing to select which format.

I think it would be much easier if the diag box remembered the last option selected, along with a checkbox:
- [ ] don't ask again

paired  with a toggle in preferences to set it to a different option.

**Comment by nlogozzo** [comment]
I feel as this is bad UX as each Filename to Tag conversion depends on the filename you are dealing with.
