### ISSUE TITLE
Cannot add album art to FLAC files

### ISSUE THREAD

**Issue by rizzolessio** [nlogozzo/NickvisionTagger#37]
When selecting any image from the file picker as a new album art for .flac files I get a `TagLib: Invalid picture block.` (log message from opening the Flatpak from terminal)
No image is added and the previous image tag is deleted.

I tried different files, sizes and square resolutions.
I'm not getting any problem on the same operation with .mp3 files.

Not sure if related, but every time the file picker is opened I get this line:
`(org.nickvision.tagger:2): GLib-CRITICAL **: 19:57:52.524: g_variant_new_string: assertion 'string != NULL' failed`

Environment: Fedora 36 / Gnome

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/commit/3eda6e00fd6dbe707455e17e9c002542521ae44e

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.8.0

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.0-beta1
