### ISSUE TITLE
Preserve modification time stamp

### ISSUE THREAD

**Issue by eldelacajita** [nlogozzo/NickvisionTagger#38]
Could there be a way to tag files while preserving the modification time stamp?

Use case: I use Tagger to tag and add album art to my recordings, but I also want to preserve the time at which a recording was taken as part of the file properties. That information is usually stored as modification time (instead of creation, I don't know why). 

For doing this, my current workflow is: keeping an unmodified version of the file, making a copy somewhere else and modifying it with Tagger, then do `touch -r original_file modified_file` to copy the time stamp, and then delete de original file.

**Comment by nlogozzo** [comment]
I will see if there is a way I can add a time stamp property where you would be able to edit it back to the original or if there is a way I can just remember it before you edit the file and set it back again after the tag edit.

**Comment by nlogozzo** [comment]
With further consideration, I feel as if this is not a feature I should implement. 
Since Tagger edits a file's metadata, updating the file's modification time stamp is thus appropriate.
I also feel as your edge case is very specific to your scenario and therefore changing this behavior would disrupt the majority of users.

**Comment by eldelacajita** [comment]
Fair enough. I was thinking of it more as an option than a fixed behavior. But if it's such an edge case for this app, I'll just look into other alternatives. Thanks for considering it!

**Comment by eldelacajita** [comment]
Oh, that's great! I think the simplest implementation would be just a checkbox in the settings. I don't need to manually modify the time stamp, I just want to preserve it.

**Comment by nlogozzo** [comment]
Oh sounds great! I'll get it implemented in V2022.8.1 and hopefully will get a Linux build for that version as well!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/commit/7f7a9b10e6a8871ecd700ae44cd89ab6144f8b48

**Comment by nlogozzo** [comment]
This was actually pretty simple to accomplish. Didn't even need to use a Qt solution. I was able to accomplish it with standard C++ :)

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/183276161-89b3377f-4782-47ba-8e58-300d81974875.png)

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/183276172-4051f9c5-6882-4aa7-abf7-ce100266429d.png)
Tooltip explanation as well

**Comment by nlogozzo** [comment]
Just need to get the linux build up and running. Use #40 to track.

**Comment by eldelacajita** [comment]
Awesome! Thanks a lot!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.0-beta1

**Comment by eldelacajita** [comment]
Wow, I just saw the GTK version is back! And with GTK4 no less! That made my day :1st_place_medal: 
Testing it right now.

**Comment by nlogozzo** [comment]
Let me know how it goes!

**Comment by nlogozzo** [comment]
@eldelacajita How's the feature looking?

**Comment by nlogozzo** [comment]
Glad it's working!
