### ISSUE TITLE
Option to add artwork to files

### ISSUE THREAD

**Issue by daudix-UFO** [nlogozzo/NickvisionTagger#4]

**Comment by nlogozzo** [comment]
Definitely on my list of todo! Will try to implement this weekend.

**Comment by nlogozzo** [comment]
Progress!!

![image](https://user-images.githubusercontent.com/17648453/171084778-497c1fbc-c437-44ec-82c0-5b931fcf1c89.png)

**Comment by daudix-UFO** [comment]
Really cool!

**Comment by daudix-UFO** [comment]
Wow!

**Comment by nlogozzo** [comment]
Almost done...just trying to get the 1MusicFile::setAlbumArt()` function to work.
Hopefully I can figure it out tonight, if not it'll get done tomorrow.

**Comment by nlogozzo** [comment]
[V2022.5.4](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.5.4)
