### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionTagger#40]
Right now V2022.8.0 only has a Windows build as that is what I used to develop the Qt rewrite. However, I don't mean to leave all my wonderful Linux users behind. For V2022.8.1, there will be a Linux build as well!

**Comment by nlogozzo** [comment]
Just have to set up my WSL2 dev environment.

**Comment by Master811129** [comment]
Just in case, Why did you rewrite your app. It already looked good.

**Comment by Master811129** [comment]
silly me #42

**Comment by nlogozzo** [comment]
I'm happy to announce, I'm rewriting back to GTK 4 and Libadwaita. Expect a release by the end of this week!

**Comment by eldelacajita** [comment]
This is awesome to hear! I've been using a "web app" created with Epiphany as a workaround, but a native GTK 4 app (or wrapper) is going to be much better. 

Will it support light/dark theme and apply it to the app itself?

**Comment by Master811129** [comment]
@nlogozzo you have a lot of energy! Do yoi want to create it with gtkmm 4 or just gtk?

**Comment by nlogozzo** [comment]
Yes, it's look and function just like the previous gtk version of the app (2022.6.3) which is still available and usable on flathub. This new version will just include some bug fixes and improvements to performance that I included in the Qt version.

**Comment by nlogozzo** [comment]
> @nlogozzo you have a lot of energy! Do yoi want to create it with gtkmm 4 or just gtk?

Haha yes I do. Windows and Qt just weren't cutting it. And I finally got fedora 36 working on my laptop with wifi drivers (had to install kernel 5.10) so now I'm good to go again :)

The gtk side will be pure C, which will be easier working with libadwaita cause there is no "adwaitamm" . And then the app functionally will be done in C++ . Just like the previous gtk version of the app was written.

**Comment by nlogozzo** [comment]
You can take a look at a skeleton architecture for the app here: https://github.com/nlogozzo/NickvisionApplication

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/commit/143e7f92f3fd841ccef879e91eeba255f3c9de08

**Comment by nlogozzo** [comment]
Look out for a release soon!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.0-beta1
