### ISSUE TITLE
Why Qt?

### ISSUE THREAD

**Issue by axel358** [nlogozzo/NickvisionTagger#42]
Why would you rewrite something so beautifully crafted in Qt?

**Comment by nlogozzo** [comment]
- Gtk and C++ sucks together. Gtkmm doesn't support libadwaita so I'm forced to use straight C when working with Gtk and trying to connect signals from C to C++ functions is a mess.
- Linux kernel 5.14 and above including the latest 5.19 broke all functionality of my laptop's WiFi card and I'm stuck with using something old like elementary os (not even fedora works) with gtk 3 and I'm forced to build everything on my desktop that has Fedora, gtk 4, and libadwaita, which defeats the purpose of developing on my laptop
- There's also some games that are windows only, not even proton or wine works with them
So for those reasons I switched back to windows 11 and it's been a pleasurable experience. For developing my applications it was either Windows App SDK or Qt. Windows App SDK is a complete pain to work with so Qt it is. I figured with Qt being cross platform, I will eventually set up a Linux VM to create builds for Linux as well.

**Comment by axel358** [comment]
Oh, i see, sorry to hear your Linux experience has been so troublesome, i hope the situation improves in the near future

**Comment by nlogozzo** [comment]
I would love to get back to Linux one day. But the fact that the intel wifi ax201 Wi-Fi drivers broke on 5.14 and still haven't been fixed with 5.19 doesn't give me hope. It's an issue a lot of ppp are haven't and it works fine in 5.10 LTS so I don't know what happened that broke it 🤷🏻‍♂️

**Comment by nlogozzo** [comment]
I'm happy to announce, I'm rewriting back to GTK 4 and Libadwaita. Expect a release by the end of this week!

**Comment by axel358** [comment]
Those are really great news!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/commit/143e7f92f3fd841ccef879e91eeba255f3c9de08

**Comment by nlogozzo** [comment]
Look out for a release soon!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.9.0-beta1

**Comment by axel358** [comment]
Awesome
