### ISSUE TITLE
Glitched UTF-8 metadata after Applying

### ISSUE THREAD

**Issue by martin-desktops** [nlogozzo/NickvisionTagger#46]
Bug occurs in Tagger 2022.9.2

# Steps to reproduce:
- Paste for instance "Mata, Maurycy Żółtański" to the Artist field
- Apply changes

Problem: Tagger no longer crashes when there is a UTF-8 character as it used to be in the past, but the metadata still isn't exported properly. Instead of polish characters there is a glitched string.

There's only one warning in console:
`(org.nickvision.tagger:2): Gtk-WARNING **: 01:07:49.577: Locale not supported by C library.`

![Screenshot from 2022-10-01 01-11-07](https://user-images.githubusercontent.com/64419373/193368003-5d44455b-f600-499c-9283-078f8e936954.png)

**Comment by nlogozzo** [comment]
Another side note: When you first open the beta version of Tagger the strings will still probably be glitched. You'll have to erase the field and fill it in again and apply the changes for the tag to encode the strings probably and after that it should all be good.

**Comment by martin-desktops** [comment]
V2022.10.0-beta2 fixed the issue. Metadata is no longer glitched. Thank you for your help!

**Comment by nlogozzo** [comment]
I'll release a stable version today

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.0
Should show up on Flathub in a few hours
