### ISSUE TITLE
reset music folder?

### ISSUE THREAD

**Issue by gforcada** [nlogozzo/NickvisionTagger#47]
Hi, thanks for the app!! 😄 
Unfortunately, I installed via gnome-software (version 2022.9.2) and after I selected my folder it crashed while loading the music files.

```
TagLib: MPEG::Header::parse() -- data is too short for an MPEG frame header.
TagLib: MPEG::Header::parse() -- data is too short for an MPEG frame header.
TagLib: ID3v2.4 no longer supports the frame type TDAT.  It will be discarded from the tag.
TagLib: MPEG::Header::parse() -- data is too short for an MPEG frame header.
TagLib: MPEG::Header::parse() -- data is too short for an MPEG frame header.
TagLib: ID3v2.4 no longer supports the frame type TSIZ.  It will be discarded from the tag.
TagLib: ID3v2.4 no longer supports the frame type TSIZ.  It will be discarded from the tag.
TagLib: ID3v2.4 no longer supports the frame type TSIZ.  It will be discarded from the tag.
TagLib: ID3v2.4 no longer supports the frame type TSIZ.  It will be discarded from the tag.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: Ogg::File::packet() -- Could not find the requested packet.
TagLib: Vorbis::File::read() - Could not find the Vorbis comment header.
```

That's the only ouput shown when running it with `flatpak run org.nickvision.tagger`.

Is there a way to get more output so it can make this bug report a bit more useful?

Now I'm in the situation that trying to open the app starts loading the music folder again and fails exactly as stated above, so I have no way to use it at all. Where can I reset the app settings so I can try to load a smaller folder and see if that works at least? 😄

**Comment by nlogozzo** [comment]
You can open the file at `~/.var/app/org.nickvision.tagger/config/Nickvision/NickvisionTagger/config.json' and remove the 'LastOpenedFolder' line or set 'RemeberLastOpenedFolder` to false to turn off the feature all together

**Comment by nlogozzo** [comment]
As far as creating a more useful log you can run `flatpak run --command=sh --devel org.nickvision.tagger` which will open your terminal in the application sandbox and then you can run `gdb /app/bin/org.nickvision.tagger` which will open the application in the C++ debugger. It will ask `Enable debuginfod for this session?` you can say `y`and then the terminal will just say `(gdb)` you then will type `run` and the application will start in the debugger.
You can then open your folder that crashes the application and you'll get a much more detailed log that you can send here.

**Comment by nlogozzo** [comment]
And just a curious question: What software did you use previously in tagging these files?

**Comment by gforcada** [comment]
Thanks for all the comments, I will have a look! 👍🏾 

As for what I was using: either nothing or rhythmbox itself.

**Comment by nlogozzo** [comment]
Ok let me know how it goes. Those error you were getting shouldn't be crashing the program but I'll look into it more myself too see. If you don't mind maybe you can attach a .zip with some of the music files from that folder so I can test it on my own machine.

**Comment by nlogozzo** [comment]
Any update?
