### ISSUE TITLE
musicbrainz integration is very imprecise

### ISSUE THREAD

**Issue by legacychimera247** [nlogozzo/NickvisionTagger#48]
i love the fact we can search for tags in musicbrainz (really love it) but i need to say that more than 50% of the times it picks the wrong record, even if i choose all songs from an album  (that maybe are parts of various compilations ond so on, the app will probably choose the compilation over the original album, that maybe is already in tags. Oh, and it's also seriously slow

Anyway to correct this? :)

**Comment by nlogozzo** [comment]
The way the `Download MusicBrainz Metdata` function works is Tagger uses the chromaprint fingerprint for the file and sends a query to AcoustId, which returns a list of MusicBrainz records, ranked from 0-100 (closer to 100, closer the match). 
Tagger then picks the highest ranked record and sends a query to MusicBrainz to get all the information it needs for the tag.
On top of that, Tagger will also query CoverArtArchieve to get an album art for the album provided by MusicBrainz and will download that image and set it as the album art.
I will try to compare our MusicBrainz metdata action to that of MusicBrainz Picard and see how Picard picks a record and try to improve the accuracy of picking a record

**Comment by nlogozzo** [comment]
As far as being slow, from the above description you can see that each file makes about 5 internet requests (AcoustID Query, MusicBrainz Record Query, MusicBrainz Release (Album) Query, CoverArtArchive Query, Downloading Cover Art Image)
This starts to pile up fast, for example, running the 'Download MusicBrainz Metadata' action of 5 files is about 25 internet requests made, which depending on your connection can be slow.
The best way that I can think of now to improve the speed is to maybe run up to 3 files on different threads handing about 15 requests at a time instead of 1 at a time per file.

**Comment by nlogozzo** [comment]
Another side note, [V2022.10.0](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.0) provides a new option in preferences called 'Overwrite Tag From MusicBrainz` in which you can turn off and whatever fields already in the tag will not be overwritten/changed by the `Download MusicBrainz Metadata` function.

**Comment by nlogozzo** [comment]
Ok, I may have found a way to speed up and improve the accuracy of the function.
`AcoustId` is able to provide musicbrainz data within the query basically reducing the number of internet requests per file.

**Comment by nlogozzo** [comment]
Speed and accuracy should be improved in [V2022.10.1-next1](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.1-next1)
Please test and let me know how it goes.

*Side Note: `Download MusicBrainz Metadata` action has been moved to a new `Web Services` button next to the `Tag Actions` button*
![Screenshot from 2022-10-02 13-31-03](https://user-images.githubusercontent.com/17648453/193467833-02f2a382-54c8-404b-8a8c-f33f36538b5a.png)

**Comment by legacychimera247** [comment]
hello, this was much faster i need to say, only problem is, since not all files as the acustid, some files are missing

as for the speed itself it was much faster, need to do further tests anyway

**Comment by nlogozzo** [comment]
To fix the issue of a file not being found with AcoustId, i added a feature in  [V2022.10.1-beta1](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.1-beta) called 'Submit to AcoustId'.
This will allow you to select a file and associate it with a MusicBrainz Recording Id that you can get from online.
