### ISSUE TITLE
ogg file sends app into crashing loop

### ISSUE THREAD

**Issue by Vittelius** [nlogozzo/NickvisionTagger#56]
The app crashes for me with this error after I accidentally tried to add my home directory:
`agLib: ID3v2.4 no longer supports the frame type TDAT.  It will be discarded from the tag.
TagLib: Vorbis::File::read() - Could not find the Vorbis comment header.
`
Since the app saves state reopening the app will just crash it again, because it automatically starts looking for files again. Moving or deleting the files also doesn't help.

**Comment by nlogozzo** [comment]
I will investigate the issue. In the mean time you can go to `~/.var/app/org.nickvision.tagger/config/Nickvision/NickvisionTagger/config.json` and set `"RememberLastOpenedFolder" : false`to prevent the application from reopening the folder and crashing automatically.

**Comment by nlogozzo** [comment]
I also don't have any ogg files to really test with. Would you be able to send me a few oggs in a .zip file here for me to test.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.4
