### ISSUE TITLE
Support for M4A Audio Files

### ISSUE THREAD

**Issue by adarsh1001** [nlogozzo/NickvisionTagger#57]
Currently, the `.m4a` audio files are not handled by Tagger. This is a popular audio format that is also supported by EasyTag and would be great if Tagger can support it as well.

**Comment by nlogozzo** [comment]
I'll add it today!

**Comment by nlogozzo** [comment]
Please Test: [V2022.10.5](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.5-beta1)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.5
