### ISSUE TITLE
Ability to edit/remove user defined tags

### ISSUE THREAD

**Issue by Elserjo** [nlogozzo/NickvisionTagger#58]
First of all, thank you for creating this program. I have noticed, that this program parses a limited amount of tags:

For example: 
1. Artist
2. Album Artist
3. Genre

However, some tracks my contain any non-standart tags:  max volume, min volume (any user defined tags). It would be great, to have ability to manipulate/remove this tags.

**Comment by Elserjo** [comment]
Something like this: 
![tagdump](https://user-images.githubusercontent.com/20269529/199430253-03a11f25-e919-46c1-8a67-0ca5dc61a453.JPG)

**Comment by nlogozzo** [comment]
#49
