### ISSUE TITLE
[Feature] Add application icon

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionTagger#6]
We need an app icon before #5 can occur.

**Comment by daudix-UFO** [comment]
I can make one, but, need some ideas what it will be?

**Comment by nlogozzo** [comment]
> I can make one, but, need some ideas what it will be?

That'd be great! I really am a terrible icon designer haha. 
Maybe a music note or a music note with lines next to it to represent files. 
Something basic that just matches gnome's icon scheme.

**Comment by daudix-UFO** [comment]
I'm working on it right now, I think I have a Idea!

**Comment by nlogozzo** [comment]
Can't wait to see it!

**Comment by daudix-UFO** [comment]
What about this?

**PNG**
![org gnome TextEditor](https://user-images.githubusercontent.com/77155297/170831354-bb9ab2fb-2a72-4cbc-8ed7-bba26c6ff2d7.png)

**SVG**
![org nlogozzo Tagger](https://user-images.githubusercontent.com/77155297/170831358-8a808258-ee26-438d-9721-db696b2f7a8d.svg)

**Comment by nlogozzo** [comment]
Wow 😮 this is amazing!! Teach me your ways haha
We have our new icon :)

**Comment by daudix-UFO** [comment]
Also, here is symbolic icon

**PNG**

![org nlogozzo Tagger (symbolic)](https://user-images.githubusercontent.com/77155297/170840099-39add73f-c516-4aad-9a10-d69935c1ae84.png)

**SVG**

![org nlogozzo Tagger (symbolic)](https://user-images.githubusercontent.com/77155297/170840115-f8ad1f4b-6958-4645-9c37-deb7f190f39a.svg)

**Comment by nlogozzo** [comment]
I'm in love! Thank you so much!

**Comment by nlogozzo** [comment]
In my next commit, I will update the readme to give special credits for you and your work with the icon :)

**Comment by daudix-UFO** [comment]
thanks, i'm really glad you like it!

**Comment by nlogozzo** [comment]
Check Readme :)

**Comment by nlogozzo** [comment]
@daudix-UFO Quick thing, using the icon-symbolic with a dark theme stays black and doesn't turn white.
![image](https://user-images.githubusercontent.com/17648453/170849347-22584731-a88e-4fad-ad99-b57fb9fd0790.png)

**Comment by jannuary** [comment]
It's in the wrong [https://docs.gtk.org/gtk4/migrating-3to4.html#review-your-use-of-icon-resources](folder.)

**Comment by daudix-UFO** [comment]
I can make white one, sorry for not answering for a long time, I was sleeping

**Comment by jannuary** [comment]
Not supposed to be white, just registered as a resource properly so that GTK can recolor it.

**Comment by daudix-UFO** [comment]
done, here all files, also, "app, symbolic" is for in-app usage, "symbolic" is for app icon in top bar

[**Files**](https://drive.google.com/drive/folders/1ZwqSY7kJBe0Y_cLVEaD3NauCvtxvoGq0?usp=sharing)

This is top bar icon, more bold is for this
![Снимок экрана от 2022-05-29 10-14-55](https://user-images.githubusercontent.com/77155297/170856868-8b12d8b7-229f-4e50-a8ad-b626a055efce.png)

**Comment by nlogozzo** [comment]
@daudix-UFO Thanks :)
Gonna figure out how to register as a resource properly to allow for recoloring

**Comment by daudix-UFO** [comment]
@nlogozzo good luck!
