### ISSUE TITLE
Advanced search information window is too large in height

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionTagger#61]
My resolution is 1360x768 and this is how advanced search information window looks on my screen:

<img src="https://i.imgur.com/DhabNHn.png" width=500px>

**Comment by nlogozzo** [comment]
The `Advanced Search Information` dialog uses a `LongMessageDialog` that should scroll the contents of the dialog. Does it scroll?
Also, what are the resolution dimensions of your screen?

**Comment by fsobolev** [comment]
No, it's not scrollable.
1360x768

**Comment by nlogozzo** [comment]
Oh, i just remembered `LongMessageDialog` is used in Tube Converter and not Tagger. (I get confused between all my apps sometimes lol) I will implement it and fix this later tonight.

**Comment by nlogozzo** [comment]
Please test [V2022.11.0-beta2](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.11.0-beta2)

**Comment by fsobolev** [comment]
I personally don't like that it also scrolls horizontally instead of text wrapping, but that's a design issue unrelated to the original problem, which is fixed. Thanks!

**Comment by nlogozzo** [comment]
Yes, it felt a little weird to me too. I will see how I can wrap it.

**Comment by fsobolev** [comment]
I can't code in C++ unfortunately, so I can't fix it myself, but using GTK inspector I found possible solution: setting the label's "wrap" property to true and "justify" to GTK_JUSTIFY_CENTER results in the original look with vertical scrolling. Hope it helps :)
<img src="https://i.imgur.com/sstT57G.png" width=500px>

**Comment by nlogozzo** [comment]
Added to longmessagedialog.cpp:
```cpp
gtk_label_set_wrap(GTK_LABEL(m_lblDescription), true);
gtk_label_set_justify(GTK_LABEL(m_lblDescription), GTK_JUSTIFY_CENTER);
```
And that fixed the issue. The fix will be included in the stable release.
