### ISSUE TITLE
Pictures not showing up under some players

### ISSUE THREAD

**Issue by cakernstock** [nlogozzo/NickvisionTagger#64]
After setting the picture for some files, their files in GNOME Nautilus no longer displayed a thumbnail. Also, the files I did this to did not show their album art in my car's infotainment system.

Doing some manual troubleshooting, I was able to narrow this down to an issue with the picture mimetype not being set. Using a different tag editor (Kid3) to fill in the picture mimetype as "image/jpeg" allowed the image to show up in thumbnails and my car again.

Also, it seems that this picture mimetype field gets clobbered even when setting unrelated fields, but that's probably a separate issue.

**Comment by nlogozzo** [comment]
I will take a look at this and make sure the mimetype is properly set.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/commit/93c378407b055a09522bfc4115f025c346e6ce6e

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.11.2
Should be available through Flathub in a few hours!
