### ISSUE TITLE
Pressing DEL removes every tag data even in input fields

### ISSUE THREAD

**Issue by sonicnkt** [nlogozzo/NickvisionTagger#65]
If you press the delete key it removes all tags, i don't mind this functionality in general but this not only happens if you focus an item in the files column but also if you are editing a specific tag. The result is that you can not use the del key in any tag editing.

I haven't been using tagger yet but i can't imagine this is the desired behavior :)

**Comment by nlogozzo** [comment]
I will see if I can disable that shortcut while a text box is active.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/commit/b91749a38519ba7f40854ccc956f34617a0741ae

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.11.2
Should be available through Flathub in a few hours!
