### ISSUE TITLE
Modification failed to apply when using external drive 

### ISSUE THREAD

**Issue by SamuDifferent** [nlogozzo/NickvisionTagger#75]
When I try to change the tags of files stored on a USB drive, no changes will be saved even after applying the changes.

**Comment by nlogozzo** [comment]
Did you install Tagger via flatpak?

**Comment by SamuDifferent** [comment]
I installed the flatpakversion via the gnome-software-store

**Comment by nlogozzo** [comment]
The flatpak version only has permission to access the home directory. 

I recommend installing Flatseal and change the permissions of Tagger to access the whole filesystem to allow it to write to a USB

**Comment by SamuDifferent** [comment]
It worked, thanks.
