### ISSUE TITLE
Join Gnome Circle

### ISSUE THREAD

**Issue by nacho-domatix** [nlogozzo/NickvisionTagger#8]
I know it is quite new, but I am really excited about the potential of the app.

Whenever Flatpak package is done,one way to reach more users and visibility would be joining [Gnome Circle](https://circle.gnome.org/). 

Let's hope this way the app can attract more community and maintainers for different distros.

**Comment by nlogozzo** [comment]
Definitely will apply once I figure out flatpak!

**Comment by nlogozzo** [comment]
See https://gitlab.gnome.org/Teams/Circle/-/issues/126
