### ISSUE TITLE
Drag 'n drop not functional

### ISSUE THREAD

**Issue by dijkstrah** [nlogozzo/NickvisionTagger#81]
After dragging and dropping a folder with music files on Tagger, nothing happens. The log registers:

org.nickvision.[24594]: Failed to receive drop data: Could not convert data from application/vnd.portal.filetransfer to GFile

**Comment by nlogozzo** [comment]
Known GTK Issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/4719

What version of GNOME are you running, if you are running GNOME? And what file manager are you using and what version?

**Comment by nlogozzo** [comment]
> > Portal doesn't support a folder dnd, only regular files https://gitlab.gnome.org/GNOME/gtk/-/issues/5348
> 
> Interesting. I immediately tried dropping a FLAC on Tagger, but nothing. No log entry either. 

Tagger is only set it accept DnD from folders...not individual files. Tagger is more of a music library (folder manager) as opposed to individual files.

But i can implement it where when you drag in a file, it will get the parent directory and open that directory so it's better than nothing.

**Comment by nlogozzo** [comment]
> Portal doesn't support a folder dnd, only regular files
> https://gitlab.gnome.org/GNOME/gtk/-/issues/5348

I guess this explains the issue then

**Comment by dijkstrah** [comment]
> > > Portal doesn't support a folder dnd, only regular files https://gitlab.gnome.org/GNOME/gtk/-/issues/5348
> > 
> > 
> > Interesting. I immediately tried dropping a FLAC on Tagger, but nothing. No log entry either.
> 
> Tagger is only set it accept DnD from folders...not individual files. Tagger is more of a music library (folder manager) as opposed to individual files.
> 
> But i can implement it where when you drag in a file, it will get the parent directory and open that directory so it's better than nothing.

No need to that, since that might feel counterintuitive. I was just testing. 

So what do I do? Wait and see? I really like the possibility to drop a folder on Tagger, since that enables a workflow that suits me. If I open my entire music directory in Tagger, all files will show in a list, which in my case is not quick but also does not give insight in which file belongs to which album, artist, etc. 

Thank you for your attention and nice little app.

**Comment by nlogozzo** [comment]
> So what do I do? Wait and see? 

Yes. Because it's a portal issue it's out of my control and there's nothing I can do to fix it.

> I really like the possibility to drop a folder on Tagger, since that enables a workflow that suits me. 

I don't know what distro you use, but if you have the AUR you can install the app from there or even build the app manually and drag and drop will work since it's not using portals when not running from flatpak.

> If I open my entire music directory in Tagger, all files will show in a list, which in my case is not quick but also does not give insight in which file belongs to which album, artist, etc.

If you have your music library separated into subfolders, you can just open the individual subfolder into Tagger instead of the whole root directory.

**Comment by dijkstrah** [comment]
> > So what do I do? Wait and see?
> 
> Yes. Because it's a portal issue it's out of my control and there's nothing I can do to fix it.
> 
> > I really like the possibility to drop a folder on Tagger, since that enables a workflow that suits me.
> 
> I don't know what distro you use, but if you have the AUR you can install the app from there or even build the app manually and drag and drop will work since it's not using portals when not running from flatpak.
> 
> > If I open my entire music directory in Tagger, all files will show in a list, which in my case is not quick but also does not give insight in which file belongs to which album, artist, etc.
> 
> If you have your music library separated into subfolders, you can just open the individual subfolder into Tagger instead of the whole root directory.

Well, I use Arch Linux and installed Tagger through the AUR. Will give a manual build a try.

**Comment by nlogozzo** [comment]
> Well, I use Arch Linux and installed Tagger through the AUR. Will give a manual build a try. 

The AUR install still had this issue?!...hmmm 🤔

**Comment by fsobolev** [comment]
> > Well, I use Arch Linux and installed Tagger through the AUR. Will give a manual build a try.
> 
> The AUR install still had this issue?!...hmmm 🤔

Portals are not only used in flatpak, and FileChooserNative uses the portal anyway if it's available:
> When the org.freedesktop.portal.FileChooser portal is available on the session bus, it is used to bring up an out-of-process file chooser. Depending on the kind of session the application is running in, this may or may not be a GTK file chooser.

So manual build will not help either, unless it's patched to use old FileChooserDialog

**Comment by dijkstrah** [comment]
> > Well, I use Arch Linux and installed Tagger through the AUR. Will give a manual build a try.
> 
> The AUR install still had this issue?!...hmmm thinking

Did a manual build from latest git, no difference.

**Comment by nlogozzo** [comment]
> Portals are not only used in flatpak, and FileChooserNative uses the portal anyway if it's available

Ah i missed understood.

> So manual build will not help either, unless it's patched to use old FileChooserDialog

@dijkstrah sorry then, there's nothing we can do unless we patch it with the old filechooserdialog or wait for the portal fix.

I really don't plan on touching the codebase until i rewrite it in C# as i did Denaro and Tube Converter.

**Comment by dijkstrah** [comment]
> > Portals are not only used in flatpak, and FileChooserNative uses the portal anyway if it's available
> 
> Ah i misunderstood.
> 
> > So manual build will not help either, unless it's patched to use old FileChooserDialog
> 
> @dijkstrah sorry then, there's nothing we can do unless we patch it with the old filechooserdialog or wait for the portal fix.
> 
> I really don't plan on touching the codebase until i rewrite it in C# as i did Denaro and Tube Converter.

That's fine to me. Good luck with the rewrite. I'll keep an eye out.
